version: '3.0'

services:
  express:
    container_name: express
    build:
      context: .
      dockerfile: ./docker/express/DockerFile
    ports:
      - 3000:3000
    volumes:
      - ./logs:/www/seco/app/logs
    restart: "unless-stopped"
    environment: 
      NODE_ENV: production
  
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
