version: '3.0'

services:
  express:
    container_name: express
    build:
      context: .
      dockerfile: ./docker/express/DockerFile
    ports:
      - 3000:3000
    volumes:
      - ./logs/app:/www/app/logs
    restart: "unless-stopped"
    environment: 
      NODE_ENV: production
  
  proxy:
    container_name: proxy
    build:
      context: .
      dockerfile: ./docker/nginx/DockerFile
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./docker/nginx/ssl:/etc/ssl/:ro
    restart: "unless-stopped"